In [1]:
import pandas as pd
pd.set_option("display.max_columns", 500)

In [2]:
df = pd.read_csv("m5_small.csv")

In [3]:
#calendar = pd.read_csv("calendar.csv")

In [4]:
df.head()

,date,item_id,dept_id,cat_id,store_id,state_id,sales,sell_price,snap_CA,snap_TX,snap_WI,event_name_1_Chanukah End,event_name_1_Christmas,event_name_1_Cinco De Mayo,event_name_1_ColumbusDay,event_name_1_Easter,event_name_1_Eid al-Fitr,event_name_1_EidAlAdha,event_name_1_Father's day,event_name_1_Halloween,event_name_1_IndependenceDay,event_name_1_LaborDay,event_name_1_LentStart,event_name_1_LentWeek2,event_name_1_MartinLutherKingDay,event_name_1_MemorialDay,event_name_1_Mother's day,event_name_1_NBAFinalsEnd,event_name_1_NBAFinalsStart,event_name_1_NewYear,event_name_1_OrthodoxChristmas,event_name_1_OrthodoxEaster,event_name_1_Pesach End,event_name_1_PresidentsDay,event_name_1_Purim End,event_name_1_Ramadan starts,event_name_1_StPatricksDay,event_name_1_SuperBowl,event_name_1_Thanksgiving,event_name_1_ValentinesDay,event_name_1_VeteransDay,event_name_2_Cinco De Mayo,event_name_2_Father's day,event_name_2_OrthodoxEaster,event_type_1_Cultural,event_type_1_National,event_type_1_Religious,event_type_1_Sporting,event_type_2_Cultural,event_type_2_Religious
0,2015-03-08,FOODS_1_001,FOODS_1,FOODS,TX_1,TX,1.0,2.24,1,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,2015-03-09,FOODS_1_001,FOODS_1,FOODS,TX_1,TX,1.0,2.24,1,1,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,2015-03-10,FOODS_1_001,FOODS_1,FOODS,TX_1,TX,0.0,2.24,1,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,2015-03-11,FOODS_1_001,FOODS_1,FOODS,TX_1,TX,0.0,2.24,0,1,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,2015-03-12,FOODS_1_001,FOODS_1,FOODS,TX_1,TX,0.0,2.24,0,1,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
df.shape

(8582723, 50)

In [6]:
#calendar['d'] = calendar['d'].str.split('_').str[1].astype(int)

In [7]:
#calendar.head()

In [8]:
#df = df.merge(calendar[['date','d']], on=['d'], how='left')

In [9]:
#df.shape

In [10]:
#df.head()

In [11]:
df = df[['date',
         'item_id',
         'dept_id',
         'cat_id',
         'store_id',
         'state_id',
         'sales',
         'sell_price',
         'snap_CA',
         'snap_TX',
         'snap_WI',
         'event_name_1_Chanukah End',
         'event_name_1_Christmas',
         'event_name_1_Cinco De Mayo',
         'event_name_1_ColumbusDay',
         'event_name_1_Easter',
         'event_name_1_Eid al-Fitr',
         'event_name_1_EidAlAdha',
         "event_name_1_Father's day",
         'event_name_1_Halloween',
         'event_name_1_IndependenceDay',
         'event_name_1_LaborDay',
         'event_name_1_LentStart',
         'event_name_1_LentWeek2',
         'event_name_1_MartinLutherKingDay',
         'event_name_1_MemorialDay',
         "event_name_1_Mother's day",
         'event_name_1_NBAFinalsEnd',
         'event_name_1_NBAFinalsStart',
         'event_name_1_NewYear',
         'event_name_1_OrthodoxChristmas',
         'event_name_1_OrthodoxEaster',
         'event_name_1_Pesach End',
         'event_name_1_PresidentsDay',
         'event_name_1_Purim End',
         'event_name_1_Ramadan starts',
         'event_name_1_StPatricksDay',
         'event_name_1_SuperBowl',
         'event_name_1_Thanksgiving',
         'event_name_1_ValentinesDay',
         'event_name_1_VeteransDay',
         'event_name_2_Cinco De Mayo',
         "event_name_2_Father's day",
         'event_name_2_OrthodoxEaster',
         'event_type_1_Cultural',
         'event_type_1_National',
         'event_type_1_Religious',
         'event_type_1_Sporting',
         'event_type_2_Cultural',
         'event_type_2_Religious']]

In [12]:
#df.to_csv("m5_small.csv", index=False)

In [13]:
df['unique_id'] = df['item_id'] + '_' + df['store_id']

print(df['unique_id'].nunique())

sampled_keys = pd.Series(df["unique_id"].unique()).sample(n=500, random_state=42)

df_subset = df[df["unique_id"].isin(sampled_keys)].copy()

18294

In [14]:
print(df_subset['unique_id'].nunique())

500

In [15]:
df_subset.drop(columns=['unique_id'], inplace=True)

In [20]:
df_subset['date'] = pd.to_datetime(df_subset['date'])

In [24]:
df_subset = df_subset[df_subset['date']<=pd.to_datetime("2016-05-20",format="%Y-%m-%d")]

In [28]:
df_subset = df_subset.reset_index(drop=True)

In [29]:
df_subset.tail(28)

,date,item_id,dept_id,cat_id,store_id,state_id,sales,sell_price,snap_CA,snap_TX,snap_WI,event_name_1_Chanukah End,event_name_1_Christmas,event_name_1_Cinco De Mayo,event_name_1_ColumbusDay,event_name_1_Easter,event_name_1_Eid al-Fitr,event_name_1_EidAlAdha,event_name_1_Father's day,event_name_1_Halloween,event_name_1_IndependenceDay,event_name_1_LaborDay,event_name_1_LentStart,event_name_1_LentWeek2,event_name_1_MartinLutherKingDay,event_name_1_MemorialDay,event_name_1_Mother's day,event_name_1_NBAFinalsEnd,event_name_1_NBAFinalsStart,event_name_1_NewYear,event_name_1_OrthodoxChristmas,event_name_1_OrthodoxEaster,event_name_1_Pesach End,event_name_1_PresidentsDay,event_name_1_Purim End,event_name_1_Ramadan starts,event_name_1_StPatricksDay,event_name_1_SuperBowl,event_name_1_Thanksgiving,event_name_1_ValentinesDay,event_name_1_VeteransDay,event_name_2_Cinco De Mayo,event_name_2_Father's day,event_name_2_OrthodoxEaster,event_type_1_Cultural,event_type_1_National,event_type_1_Religious,event_type_1_Sporting,event_type_2_Cultural,event_type_2_Religious
219723,2016-04-23,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219724,2016-04-24,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219725,2016-04-25,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219726,2016-04-26,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219727,2016-04-27,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219728,2016-04-28,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219729,2016-04-29,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,2.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219730,2016-04-30,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
219731,2016-05-01,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,2.0,6.97,1,1,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
219732,2016-05-02,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,1,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219733,2016-05-03,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,1,1,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219734,2016-05-04,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,1,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219735,2016-05-05,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,1,1,1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
219736,2016-05-06,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,1,1,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219737,2016-05-07,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,2.0,6.97,1,1,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219738,2016-05-08,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,1,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
219739,2016-05-09,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,1,1,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219740,2016-05-10,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,1,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219741,2016-05-11,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,0,1,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219742,2016-05-12,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,0,1,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219743,2016-05-13,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,0,1,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219744,2016-05-14,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,0,0,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219745,2016-05-15,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,0,1,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219746,2016-05-16,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219747,2016-05-17,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,0.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219748,2016-05-18,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219749,2016-05-19,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
219750,2016-05-20,HOUSEHOLD_2_507,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,1.0,6.97,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [30]:
df_subset.to_csv("m5_tiny.csv", index=False)